"""
Dagster asset graph for the MetricVault pipeline: Stripe extract -> dbt
build -> dbt test -> semantic layer refresh -> Tableau extract refresh,
with the Finance reconciliation check as a scheduled asset that alerts
on control failure.

This is written as real, importable Dagster asset definitions (not
pseudocode), and is executed in this repo's verification run via
`dagster asset materialize`, see docs/dagster_run_log.txt for the
actual run output. The dbt-build step shells out to the same `dbt
build` command verified manually elsewhere in this repo; wiring it
through dagster-dbt's native asset loader is the production upgrade
path, noted inline below.
"""
import subprocess
import os
import duckdb
from dagster import asset, AssetExecutionContext, MaterializeResult, MetadataValue, Definitions, AssetCheckResult, AssetCheckExecutionContext, asset_check

DBT_PROJECT_DIR = "../dbt"
DB_PATH = "../dbt/metricvault.duckdb"


@asset(group_name="ingestion", description="Extracts Stripe objects and loads them into the RAW schema. Production version calls the real Stripe API; this repo's version loads the synthetic CSVs generated by data/generate_stripe_data.py.")
def stripe_extract(context: AssetExecutionContext) -> MaterializeResult:
    result = subprocess.run(
        ["python3", "load_raw_data.py"],
        cwd=f"{DBT_PROJECT_DIR}/scripts",
        capture_output=True, text=True,
    )
    context.log.info(result.stdout)
    if result.returncode != 0:
        raise Exception(f"stripe_extract failed: {result.stderr}")

    con = duckdb.connect(DB_PATH)
    row_counts = {}
    for t in ["customers", "subscriptions", "plan_changes", "invoices", "charges", "refunds"]:
        row_counts[t] = con.execute(f"select count(*) from raw_stripe.{t}").fetchone()[0]
    con.close()

    return MaterializeResult(
        metadata={f"rows_{k}": MetadataValue.int(v) for k, v in row_counts.items()}
    )


@asset(group_name="transformation", deps=[stripe_extract], description="Runs dbt build (staging -> intermediate -> marts) plus all dbt tests. Production upgrade path: swap this subprocess call for dagster-dbt's DbtCliResource + @dbt_assets decorator, which maps each dbt model to its own Dagster asset node automatically from the manifest.")
def dbt_build(context: AssetExecutionContext) -> MaterializeResult:
    result = subprocess.run(
        ["dbt", "build"],
        cwd=DBT_PROJECT_DIR,
        env={**os.environ, "DBT_PROFILES_DIR": "."},
        capture_output=True, text=True,
    )
    context.log.info(result.stdout[-3000:])
    if result.returncode != 0:
        raise Exception(f"dbt build failed:\n{result.stdout[-2000:]}")

    return MaterializeResult(metadata={"dbt_build_log_tail": MetadataValue.text(result.stdout[-1500:])})


@asset(group_name="transformation", deps=[dbt_build], description="Regenerates dbt docs (lineage graph, catalog) so the human-readable lineage site stays current with every run.")
def dbt_docs(context: AssetExecutionContext) -> MaterializeResult:
    result = subprocess.run(
        ["dbt", "docs", "generate"],
        cwd=DBT_PROJECT_DIR,
        env={**os.environ, "DBT_PROFILES_DIR": "."},
        capture_output=True, text=True,
    )
    context.log.info(result.stdout[-1000:])
    if result.returncode != 0:
        raise Exception(f"dbt docs generate failed: {result.stderr}")
    return MaterializeResult()


@asset(group_name="semantic_layer", deps=[dbt_build], description="Production step: dbt sl validate / MetricFlow query cache warm. This repo's version validates the semantic_models.yml and metrics.yml files parse and every metric's referenced measure exists on its semantic model, a lighter-weight local stand-in for a live MetricFlow server validation call.")
def semantic_layer_refresh(context: AssetExecutionContext) -> MaterializeResult:
    import yaml
    with open("../semantic_layer/semantic_models.yml") as f:
        semantic_models = yaml.safe_load(f)["semantic_models"]
    with open("../semantic_layer/metrics.yml") as f:
        metrics = yaml.safe_load(f)["metrics"]

    all_measures = set()
    for sm in semantic_models:
        for m in sm.get("measures", []):
            all_measures.add(m["name"])

    validated = 0
    for metric in metrics:
        if metric["type"] == "simple":
            measure_name = metric["type_params"]["measure"]
            if measure_name not in all_measures:
                raise Exception(f"Metric '{metric['name']}' references undefined measure '{measure_name}'")
            validated += 1

    context.log.info(f"Validated {validated} simple metrics against {len(all_measures)} defined measures")
    return MaterializeResult(metadata={
        "metrics_validated": MetadataValue.int(validated),
        "semantic_models": MetadataValue.int(len(semantic_models)),
    })


@asset(group_name="bi", deps=[dbt_build], description="Refreshes the Tableau extract off the certified marts. Production version calls the Tableau REST API's refreshExtract endpoint; this repo's version confirms the marts the extract depends on are queryable and non-empty.")
def tableau_extract_refresh(context: AssetExecutionContext) -> MaterializeResult:
    con = duckdb.connect(DB_PATH)
    checks = {}
    for table in ["fct_mrr_movements", "fct_subscription_revenue", "fct_finance_reconciliation"]:
        count = con.execute(f"select count(*) from main_marts.{table}").fetchone()[0]
        checks[table] = count
        if count == 0:
            raise Exception(f"{table} is empty, refusing to refresh Tableau extract")
    con.close()
    return MaterializeResult(metadata={f"{k}_rows": MetadataValue.int(v) for k, v in checks.items()})


@asset_check(asset=dbt_build, description="SOX control: fails the check (not the pipeline) if any month in the Finance reconciliation table exceeds the 2% variance threshold, surfacing it for review without blocking downstream BI refresh.")
def finance_reconciliation_check(context: AssetCheckExecutionContext) -> AssetCheckResult:
    con = duckdb.connect(DB_PATH)
    fails = con.execute("""
        select month, variance_pct from main_marts.fct_finance_reconciliation
        where control_status != 'PASS'
        order by month
    """).fetchall()
    con.close()

    if fails:
        detail = "; ".join(f"{m}: {v*100:.1f}%" for m, v in fails)
        return AssetCheckResult(
            passed=False,
            metadata={"failing_months": MetadataValue.text(detail), "fail_count": MetadataValue.int(len(fails))},
            description=f"{len(fails)} month(s) exceed the 2% reconciliation threshold: {detail}",
        )
    return AssetCheckResult(passed=True, description="All months reconcile within the 2% control threshold.")


defs = Definitions(
    assets=[stripe_extract, dbt_build, dbt_docs, semantic_layer_refresh, tableau_extract_refresh],
    asset_checks=[finance_reconciliation_check],
)
